org: tomasmenito
app: magneto
service: magneto

frameworkVersion: '2'

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  runtime: python3.9
  lambdaHashingVersion: '20201221'
  iamRoleStatements:
    - Effect: "Allow"
      Action:
       - dynamodb:Query
       - dynamodb:PutItem
       - dynamodb:GetItem
       - dynamodb:UpdateItem
      Resource: 
        Fn::GetAtt:
          - mutant
          - Arn

resources:
  Resources:
    mutant:
      Type: AWS::DynamoDB::Table
      Properties: 
        AttributeDefinitions: 
          - AttributeName: is_mutant
            AttributeType: N 
          - AttributeName: dna_rows
            AttributeType: S
        KeySchema: 
          - AttributeName: is_mutant
            KeyType: HASH
          - AttributeName: dna_rows
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: mutant
          

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-wsgi
  - serverless-python-requirements
